# Generated by Django 4.1.2 on 2022-10-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_level_access_network_devices_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name': 'Учёт запросов', 'verbose_name_plural': 'Учёт запросов'},
        ),
        migrations.AlterModelOptions(
            name='fail_tries',
            options={'verbose_name': 'Неуспешные попытки подключения', 'verbose_name_plural': 'Неуспешные попытки подключения'},
        ),
        migrations.AlterModelOptions(
            name='level_access_network',
            options={'verbose_name': 'Уровень доступа к сети', 'verbose_name_plural': 'Уровень доступа к сети'},
        ),
        migrations.AlterModelOptions(
            name='level_access_network_devices',
            options={'verbose_name': 'Уровень доступа к сетевому оборудованию ', 'verbose_name_plural': 'Уровень доступа к сетевому оборудованию'},
        ),
        migrations.AlterModelOptions(
            name='nas',
            options={'verbose_name': 'Сервер сетевого доступа', 'verbose_name_plural': 'Сервер сетевого доступа'},
        ),
        migrations.AlterModelOptions(
            name='nas_port_type',
            options={'verbose_name': 'Порт подключения', 'verbose_name_plural': 'Порт подключения'},
        ),
        migrations.AlterModelOptions(
            name='user_groups',
            options={'verbose_name': 'Группы пользователей ', 'verbose_name_plural': 'Группы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
